package Frontend;

import Backend.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FrmTransaksi
     */
    
    public FrmTransaksi() {
        initComponents();
        tampilkanDataTransaksi();
        tampilkanDataKasir();
        tampilkanDataPembeli();
        tampilkanDataObat();
        kosongkanForm();
    }
    
    public boolean isValidDate(String inDate) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        dateFormat.setLenient(false);
        try {
            dateFormat.parse(inDate.trim());
        } catch (ParseException pe) {
            return false;
        }
        return true;
    }
    
    public void kosongkanForm(){
        txtTransaksi.setText("0");
        txtTanggalTransaksi.setText("");
        txtIdKasir.setText("");
        txtIdPembeli.setText("");
        txtIdObat.setText("");
        txtNamaKasir.setText("Nama Kasir");
        txtNamaPembeli.setText("Nama Pembeli");
        txtNamaObat.setText("Nama Obat");
        txtHargaObat.setText("");
        txtJumlah.setText("");
        txtTotal.setText("0");
    }
    
    private Kasir cariKasir(int idKasir){
        Kasir ka = new Kasir().getById(idKasir);
        if(ka != null){
            return ka;
        } 
       return null;
    }
    
    private Pembeli cariPembeli(int idPembeli){
        Pembeli pe = new Pembeli().getById(idPembeli);
        if(pe != null){
            return pe;
        } 
       return null;
    }
    
    private Obat cariObat(int idObat){
        Obat ob = new Obat().getById(idObat);
        if(ob != null){
            return ob;
        } 
       return null;
    }
    
    public final void tampilkanDataTransaksi(){ 
        String[] kolom = {"ID", "Tanggal Transaksi", "Nama Kasir", "Nama Pembeli", "Obat", "Jumlah", "Total Biaya"};
        ArrayList<Transaksi> list = new Transaksi().getAll();
        Object rowData[] = new Object[7];
        
        tblTransaksi.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (Transaksi tr : list ) {
            rowData[0] = tr.getIdTransaksi();
            rowData[1] = tr.getTanggalTransaksi();
            rowData[2] = tr.getKasir().getNamaKasir();
            rowData[3] = tr.getPembeli().getNamaPembeli();
            rowData[4] = tr.getObat().getNamaObat();
            rowData[5] = tr.getJumlah();
            rowData[6] = tr.getTotalBiaya();
        
            ((DefaultTableModel)tblTransaksi.getModel()).addRow(rowData);
        }
    }
    
    public final void tampilkanDataKasir(){ 
        String[] kolom = {"ID", "Nama Kasir"};
        ArrayList<Kasir> list = new Kasir().getAll();
        Object rowData[] = new Object[2];
        
        tblKasir.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (Kasir ka : list ) {
            rowData[0] = ka.getIdKasir();
            rowData[1] = ka.getNamaKasir();
        
            ((DefaultTableModel)tblKasir.getModel()).addRow(rowData);
        }
    }
    
    public final void tampilkanDataPembeli(){ 
        String[] kolom = {"ID", "Nama Pembeli"};
        ArrayList<Pembeli> list = new Pembeli().getAll();
        Object rowData[] = new Object[2];
        
        tblPembeli.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (Pembeli pe : list ) {
            rowData[0] = pe.getIdPembeli();
            rowData[1] = pe.getNamaPembeli();
        
            ((DefaultTableModel)tblPembeli.getModel()).addRow(rowData);
        }
    }
    
    public final void tampilkanDataObat(){ 
        String[] kolom = {"ID", "Nama obat"};
        ArrayList<Obat> list = new Obat().getAll();
        Object rowData[] = new Object[2];
        
        tblObat.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (Obat ob : list ) {
            rowData[0] = ob.getIdObat();
            rowData[1] = ob.getNamaObat();
        
            ((DefaultTableModel)tblObat.getModel()).addRow(rowData);
        }
    }
    
    private boolean checkInput(String tanggalTransaksi) {
        boolean res = true;

        if(tanggalTransaksi.equals("")){
            res = false;
        } 
        return res;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTransaksi = new javax.swing.JTextField();
        txtTanggalTransaksi = new javax.swing.JTextField();
        txtIdKasir = new javax.swing.JTextField();
        txtIdPembeli = new javax.swing.JTextField();
        txtIdObat = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        btnTotal = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCariKasir = new javax.swing.JButton();
        btnCariPembeli = new javax.swing.JButton();
        btnCariObat = new javax.swing.JButton();
        txtNamaKasir = new javax.swing.JLabel();
        txtNamaPembeli = new javax.swing.JLabel();
        txtNamaObat = new javax.swing.JLabel();
        btnHarga = new javax.swing.JButton();
        txtHargaObat = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblObat = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKasir = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPembeli = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDiskon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSAKSI");

        jLabel1.setText("ID Transaksi");

        jLabel2.setText("ID Kasir");

        jLabel3.setText("ID Pembeli");

        jLabel4.setText("ID Obat");

        jLabel5.setText("Tanggal Transaksi");

        jLabel6.setText("Jumlah");

        txtTransaksi.setEnabled(false);

        txtIdObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdObatActionPerformed(evt);
            }
        });

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel7.setText("Format : YYYY/MM/DD");

        jLabel8.setText("Pencarian");

        btnCari.setText("Cari");

        btnTotal.setText("Total Biaya");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel9.setText("FORM DATA TRANSAKSI");

        btnCariKasir.setText("Cari");
        btnCariKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariKasirActionPerformed(evt);
            }
        });

        btnCariPembeli.setText("Cari");
        btnCariPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPembeliActionPerformed(evt);
            }
        });

        btnCariObat.setText("Cari");
        btnCariObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariObatActionPerformed(evt);
            }
        });

        txtNamaKasir.setText("Nama Kasir");

        txtNamaPembeli.setText("Nama Pembeli");

        txtNamaObat.setText("Nama Obat");

        btnHarga.setText("Harga Satuan");
        btnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaActionPerformed(evt);
            }
        });

        tblObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblObat);

        tblKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblKasir);

        tblPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblPembeli);

        jLabel10.setText("Tabel Kasir");

        jLabel11.setText("Tabel Pembeli");

        jLabel12.setText("Tabel Obat");

        txtDiskon.setText("Diskon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6))
                                .addComponent(btnTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCari))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(8, 8, 8)
                                            .addComponent(btnTambah)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnSimpan)
                                            .addGap(48, 48, 48))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtJumlah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtHargaObat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(txtIdPembeli, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtIdKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtIdObat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btnCariKasir)
                                                        .addComponent(btnCariPembeli)
                                                        .addComponent(btnCariObat)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtTotal)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtDiskon)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNamaKasir)
                                                .addComponent(txtNamaObat)
                                                .addComponent(txtNamaPembeli))
                                            .addGap(36, 36, 36)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtTanggalTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel7))
                                            .addComponent(txtTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(btnHapus))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel9)))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTanggalTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdKasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCariKasir)
                            .addComponent(txtNamaKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIdPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCariPembeli)
                            .addComponent(txtNamaPembeli))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIdObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCariObat)
                            .addComponent(txtNamaObat))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHarga)
                            .addComponent(txtHargaObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTotal)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiskon)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnCari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdObatActionPerformed

    private void btnCariKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKasirActionPerformed
        // TODO add your handling code here:
        if(txtIdKasir.getText().equals("")){
            JOptionPane.showMessageDialog(this, "ID Kasir harus diisi !"); 
        }else {
            Kasir ka = cariKasir(Integer.parseInt(txtIdKasir.getText()));
            if(ka.getIdKasir() != 0){
                txtIdKasir.setText(String.valueOf(ka.getIdKasir()));
                txtNamaKasir.setText(ka.getNamaKasir());
            } else {
                JOptionPane.showMessageDialog(this, "ID Kasir tidak ditemukan!"); 
                txtIdKasir.setText("");
                txtNamaKasir.setText("Nama Kasir");
            }
        }
    }//GEN-LAST:event_btnCariKasirActionPerformed

    private void btnCariPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPembeliActionPerformed
        // TODO add your handling code here:
        if(txtIdPembeli.getText().equals("")){
            JOptionPane.showMessageDialog(this, "ID Pembeli harus diisi !"); 
        }else {
            Pembeli pe = cariPembeli(Integer.parseInt(txtIdPembeli.getText()));
            if(pe.getIdPembeli() != 0){
                txtIdPembeli.setText(String.valueOf(pe.getIdPembeli()));
                txtNamaPembeli.setText(pe.getNamaPembeli());
            } else {
                JOptionPane.showMessageDialog(this, "ID Pembeli tidak ditemukan!"); 
                txtIdPembeli.setText("");
                txtNamaPembeli.setText("Nama Pembeli");
            }
        }
    }//GEN-LAST:event_btnCariPembeliActionPerformed

    private void btnCariObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariObatActionPerformed
        // TODO add your handling code here:
        if(txtIdObat.getText().equals("")){
            JOptionPane.showMessageDialog(this, "ID Obat harus diisi !"); 
        }else {
            Obat ob = cariObat(Integer.parseInt(txtIdObat.getText()));
            if(ob.getIdObat() != 0){
                txtIdObat.setText(String.valueOf(ob.getIdObat()));
                txtNamaObat.setText(ob.getNamaObat());
            } else {
                JOptionPane.showMessageDialog(this, "ID Obat tidak ditemukan!"); 
                txtIdObat.setText("");
                txtNamaObat.setText("Nama Obat");
            }
        }
    }//GEN-LAST:event_btnCariObatActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Transaksi tr = new Transaksi();   
        Kasir ka = cariKasir(Integer.parseInt(txtIdKasir.getText()));
        Pembeli pe = cariPembeli(Integer.parseInt(txtIdPembeli.getText()));
        Obat ob = cariObat(Integer.parseInt(txtIdObat.getText()));
        Kasir newka = new Kasir().getById(ka.getIdKasir());
        Pembeli newpe = new Pembeli().getById(pe.getIdPembeli());
        Obat newob = new Obat().getById(ob.getIdObat());
        tr.setIdTransaksi(Integer.parseInt(txtTransaksi.getText()));
        tr.setTanggalTransaksi(txtTanggalTransaksi.getText());
        tr.setKasir(newka);
        tr.setPembeli(newpe);
        tr.setObat(newob);
        tr.setJumlah(Integer.parseInt(txtJumlah.getText()));
        tr.setTotalBiaya(Integer.parseInt(txtTotal.getText()));
        tr.save();
        tampilkanDataTransaksi();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(tblTransaksi.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(this, "Silahkan pilih data yang akan dihapus!");
            kosongkanForm();
        }else {
            DefaultTableModel model = (DefaultTableModel)tblTransaksi.getModel();
            int row = tblTransaksi.getSelectedRow();
            
            Transaksi tr = new Transaksi().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
            tr.delete();
            kosongkanForm();
            tampilkanDataTransaksi();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        int totalHarga;
        int jumlah;
        int harga;
        int diskon;
        jumlah = Integer.parseInt(txtJumlah.getText());
        harga = Integer.parseInt(txtHargaObat.getText());
        Pembeli pe = cariPembeli(Integer.parseInt(txtIdPembeli.getText()));
        if (pe.getIdMember() != 0){
            diskon = (harga*5/100)*jumlah;
            totalHarga = (jumlah * harga) - diskon;
            txtTotal.setText("" + totalHarga);
            txtDiskon.setText("Diskon: " + diskon);
        } else {
            totalHarga = (jumlah * harga);
            txtTotal.setText("" + totalHarga);
            txtDiskon.setText("Diskon: 0");
        }
    }//GEN-LAST:event_btnTotalActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblTransaksi.getModel();
        int row = tblTransaksi.getSelectedRow();

        txtTransaksi.setText(model.getValueAt(row, 0).toString());
        txtTanggalTransaksi.setText(model.getValueAt(row, 1).toString());
        txtNamaKasir.setText(model.getValueAt(row, 2).toString());
        txtNamaPembeli.setText(model.getValueAt(row, 3).toString());
        txtNamaObat.setText(model.getValueAt(row, 4).toString());
        txtJumlah.setText(model.getValueAt(row, 5).toString());
        txtTotal.setText(model.getValueAt(row, 6).toString());
        
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        // TODO add your handling code here:
        if(txtIdObat.getText().equals("")){
            JOptionPane.showMessageDialog(this, "ID Obat harus diisi !"); 
        }else {
            Obat ob = cariObat(Integer.parseInt(txtIdObat.getText()));
            if(ob.getIdObat() != 0){
                txtIdObat.setText(String.valueOf(ob.getIdObat()));
                txtHargaObat.setText(String.valueOf(ob.getHarga()));
            } else {
                JOptionPane.showMessageDialog(this, "ID Obat tidak ditemukan!"); 
                txtIdObat.setText("");
                txtHargaObat.setText("");
            }
        }
    }//GEN-LAST:event_btnHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCariKasir;
    private javax.swing.JButton btnCariObat;
    private javax.swing.JButton btnCariPembeli;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblKasir;
    private javax.swing.JTable tblObat;
    private javax.swing.JTable tblPembeli;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtCari;
    private javax.swing.JLabel txtDiskon;
    private javax.swing.JTextField txtHargaObat;
    private javax.swing.JTextField txtIdKasir;
    private javax.swing.JTextField txtIdObat;
    private javax.swing.JTextField txtIdPembeli;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JLabel txtNamaKasir;
    private javax.swing.JLabel txtNamaObat;
    private javax.swing.JLabel txtNamaPembeli;
    private javax.swing.JTextField txtTanggalTransaksi;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTransaksi;
    // End of variables declaration//GEN-END:variables
}
